services:
  - type: web
    name: rnn-waterlevel
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api2.py
    envVars:
      - key: FLASK_ENV
        value: production
